### ISSUE TITLE
The spelling things & some little advices

### ISSUE THREAD

**Issue by WangNianyi2001** [centurionace/BookRecommendationProject#1]
* > One important *thinhg* is that userIds must be numbers of eight digits or more
* Some sentences have punctuation marks at the end, but some don't. 
* A fuzzy searching is more user-friendly, users don't have to spell the exact words in the title. 
  You could find some articles about *Edit Distance* on the Internet. 
* Naming format
  Some comments are beginning with uppercase letters, but others are lowercase letter. 
  Some functions are beginning with lowercase letters. 
* Over-encapsulation
  Function addBookToLibrary(Book) in User.java is totally unnecessary, raw sentences are clearer. 
  Careless error handler: many functions only print the error infos when catches an error. This is horrible in real environment.

**Comment by centurionace** [comment]
Gotcha. Thanks brother
